### PR TITLE
Create Spork::VERSION

### PR DESCRIPTION
**Pull request by ghost**
Hi Tim, 

Here's a solution for Spork to know its own version number. Could you pull this?

This follows the version example from Carl Lerche and Yehuda Katz in the bundler gem:
- New file /lib/spork/version.rb that defines Spork::VERSION
- Update to spork.gemspec to require the version.rb for Spork::VERSION

Note that I bumped the version to rc10 to show how it works-- you may want to alter this. The gem builds fine on my setup.

My contact info is joelparkerhenderson on Gmail and Google Talk if you'd like to ask about it. 

Thanks,
Joel

### CODE REVIEW

**Comment by d11wtq** [comment]
Joel, I think maybe you forgot to commit the version.rb file?  The diff is only showing a change in the gemspec.

**Comment by parndt** [comment]
@SixArm is there a `lib/spork/version.rb` missing from the pull request?

**Comment by SixArm** [comment]
Yes - pushing it now. Thanks for the heads up.

**Comment by SixArm** [comment]
@Tim be sure to update the version # for the current spork.

**Comment by sahilm** [comment]
Closing old pull requests. Please send new ones if this is still an issue.

**Pull request closed without merging**
