### PR TITLE
Cucumber::StepMother has been deprecated

### PR DESCRIPTION
**Pull request by bcardarella**
Now using Cucumber::Runtime

### CODE REVIEW

**Comment by bcardarella** [comment]
Are there any issues with this patch?

**Comment by bcardarella** [comment]
Bueller? Bueller?

**Comment by timcharper** [comment]
I don't see anything wrong with it, I'll pull it in.

Sorry it took so long, I took a six-month hiatus from open-source work.

**Comment by bcardarella** [comment]
Awesome. Thanks!

**Pull request closed without merging**
