### PR TITLE
Windows fix #79

### LINKED ISSUE #79: JRuby: you must call Spork.using_spork! before starting the server
I receive the following backtrace when executing spork against spork-0a437df35201 (0.9.0.rc2) and JRuby 1.5.3. I have run $ bundle exec spork --bootstrap and followed the instructions there.

```
$ bundle exec spork
Using RSpec
-- Starting to fill pool...
   Wait until at least one slave is provided before running tests...
** CTRL+BREAK to stop Spork and kill all ruby slave processes **
you must call Spork.using_spork! before starting the server (RuntimeError)
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/lib/spork/server.rb:25:in `listen'
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/lib/spork/server.rb:20:in `run'
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/bin/../lib/spork/runner.rb:75:in `run'
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/bin/../lib/spork/runner.rb:10:in `run'
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/bin/spork:10
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/bin/spork:19:in `load'
/home/shacjo/.rvm/gems/jruby-1.5.3/bin/spork:19
```

Note that I did discover that the following line was commented out: http://github.com/timcharper/spork/blob/master/lib/spork/run_strategy/magazine/magazine_slave.rb#L14

It is unclear to me whether something else should be calling Spork.using_spork! or whether this is the correct place for it and it was inadvertently disabled.

Thanks for your help

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by 2potatocakes** [comment]
Cheers for the patch voxix, works for me ;)

**Comment by jarmo** [comment]
Working for me too.

**Comment by timcharper** [comment]
Change integrated in spork-0.9.0rc4.  Thanks!

**Comment by timcharper** [comment]
integrated in 0.9.0rc4 (in a slightly altered form). Thank you!

**Comment by voxik** [comment]
Nice! Thank you.

**Pull request closed without merging**
